services:
  backend:
    image: ${DOCKER_USERNAME}/transcript-chat-backend:${VERSION}
    container_name: transcript-chat-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - ./transcripts:/app/transcripts
      - ./storage:/app/storage
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

  frontend:
    image: ${DOCKER_USERNAME}/transcript-chat-frontend:${VERSION}
    container_name: transcript-chat-frontend
    restart: always
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  storage: 