version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: transcript-chat-backend
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - ./transcripts:/app/transcripts
      - ./storage:/app/storage
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: transcript-chat-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:10000
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  storage:
