version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: transcript-chat-backend
    ports:
      - "10000:10000"
    env_file:
      - .env
    networks:
      - app-network
    restart: "no"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: transcript-chat-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:10000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
