services:
  - type: web
    name: transcript-chat-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PORT
        value: "10000"
    port: 10000
    healthCheckPath: /health
    healthCheckTimeout: 2400
    buildCommand: docker build -t transcript-chat-backend -f Dockerfile.backend .

  - type: web
    name: transcript-chat-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    envVars:
      - key: BACKEND_URL
        value: https://transcript-chat-backend.onrender.com
    buildCommand: docker build -t transcript-chat-frontend -f Dockerfile.frontend . 