services:
  - type: web
    name: transcript-chat-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    healthCheckPath: /health
    healthCheckTimeout: 1800
    startCommand: /app/start.sh
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: transcript-chat-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    envVars:
      - key: PORT
        value: 8501
      - key: BACKEND_URL
        fromService:
          name: transcript-chat-backend
          type: web
          property: host 