services:
  - type: web
    name: door-ai-backend
    env: python
    region: oregon
    plan: standard
    buildCommand: |
      pip install -r requirements.txt
      python build_index.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    healthCheckTimeout: 300
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.6

  - type: web
    name: door-ai-frontend
    env: python
    region: oregon
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: BACKEND_URL
        value: https://door-ai-backend.onrender.com 